FROM nvcr.io/nvidia/pytorch:25.05-py3

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    ninja-build \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip setuptools wheel


RUN pip install --no-cache-dir \
    "git+https://github.com/Dao-AILab/flash-moba.git@v2.0.0" 
