FROM nvcr.io/nvidia/pytorch:25.05-py3
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    ninja-build \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip setuptools wheel
RUN python3 -m pip install packaging ninja
RUN git clone https://github.com/mit-han-lab/flash-moba.git && cd flash-moba \
    && MAX_JOBS=2 python setup.py install